# Generated by Django 4.0.1 on 2022-01-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otd_type', models.TextField(verbose_name='OfTheDay_Type')),
                ('sub_type', models.TextField(verbose_name='Sub_Type')),
                ('api_source', models.TextField(verbose_name='Api_Source')),
                ('data', models.TextField(verbose_name='Data')),
                ('otd_date', models.TextField(verbose_name='OfTheDay_Date')),
            ],
        ),
    ]
